# Generated by Django 4.0 on 2021-12-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('PlanID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.TextField(verbose_name='ID')),
                ('PlanFrom', models.DateTimeField(verbose_name='Start')),
                ('PlanTo', models.DateTimeField(verbose_name='End')),
                ('PlanAbout', models.TextField(verbose_name='About')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['PlanFrom'],
            },
        ),
    ]
