# Generated by Django 4.0 on 2021-12-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Title',
            field=models.TextField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
