# Generated by Django 4.0 on 2021-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='UserID',
            field=models.TextField(default='test', verbose_name='ID'),
        ),
    ]
