# Generated by Django 4.0 on 2022-01-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['PlanFrom', 'PlanTo']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='Color',
            field=models.TextField(default='black', verbose_name='表示色'),
        ),
    ]
